spring.application.name=auth-service
server.port=8080
spring.profiles.active=local
spring.datasource.url=jdbc:postgresql://postgres:5432/auth_db
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# RabbitMQ
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

jwt.secret=UmaSenhaBemLongaParaNossaAplicacao

app.magic-link.ttl-seconds=900
app.magic-link.verify-url-base=localhost:8080/auth/login/magic/verify

eureka.client.service-url.defaultZone=http://service-discovery:8080/eureka
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
