version: '3.9'

services:
  service-discovery:
    build:
      context: ./service-discovery
    container_name: service-discovery
    ports:
      - "8080:8080"
    networks:
      - app-network

  gateway-service:
    build:
      context: ./gateway-service
    container_name: gateway-service
    ports:
      - "8083:8080"
    depends_on:
      - service-discovery
    networks:
      - app-network

  auth-service:
    build:
      context: ./auth-service
    container_name: auth-service
    ports:
      - "8084:8080"
    depends_on:
      - service-discovery
    networks:
      - app-network

  user-service:
    build:
      context: ./user-service
    container_name: user-service
    ports:
      - "8086:8080"
    depends_on:
      - service-discovery
    networks:
      - app-network

  events-service:
    build:
      context: ./events-service
    container_name: events-service
    ports:
      - "8081:8080"
    depends_on:
      - service-discovery
    networks:
      - app-network

  guest-service:
    build:
      context: ./guest-service
    container_name: guest-service
    ports:
      - "8082:8080"
    depends_on:
      - service-discovery
    networks:
      - app-network

  item-service:
    build:
      context: ./item-service
    container_name: item-service
    ports:
      - "8085:8080"
    depends_on:
      - service-discovery
    networks:
      - app-network

  notification-service:
    build:
      context: ./notification-service
    container_name: notification-service
    ports:
      - "8087:8080"
    depends_on:
      - service-discovery
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - gateway-service
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
