events {}

http {
    upstream events_svc {
        server events-service:8080;
    }

    upstream item_svc {
        server item-service:8080;
    }
    
    upstream guest_svc {
        server guest-service:8080;
    }
    
    upstream user_svc {
        server user-service:8080;
    }

    upstream notification_svc {
        server notification-service:8080;
    }

    upstream apiservice {
        server events-service:8080 max_fails=2 fail_timeout=60s;
        server item-service:8080;
        server guest-service:8080;
        server user-service:8080;
        server notification-service:8080;
    }

    server {
        listen 80;

        location /events/ {
            proxy_pass http://events_svc/;
            proxy_set_header Host $host;
        }

        location /guest/ {
            proxy_pass http://guest_svc/;
            proxy_set_header Host $host;
        }

        location /item/ {
            proxy_pass http://item_svc/;
            proxy_set_header Host $host;
        }

        location /notification/ {
            proxy_pass http://notification_svc/;
            proxy_set_header Host $host;
        }

        location /user/ {
            proxy_pass http://user_svc/;
            proxy_set_header Host $host;
        }

        location / {
            proxy_pass http://apiservice/;
            proxy_set_header Host $host;
        }
    }
}
